### ISSUE TITLE
several pages in pdf-file

### ISSUE THREAD

**Issue by Inkognitoo** [thnew/Pdf2Png#1]
Hello! 
How i can get several png-image if i have several paged in png-file?

**Comment by thnew** [comment]
Hi, I'm sorry this case is not covered by my module. I think the best way to do this would be to fork my project and add some parameters to the part where I start the ghostscript executable so you can catch specific pages out of the PDF and then loop over the pages.
You can determine the amount of pages of a PDF file by using ghostscript too. Take a look at my module pdf_page_count (https://www.npmjs.com/package/pdf_page_count). There you should find out how to get ghostscript to tell you the amount of pages.

**Comment by Inkognitoo** [comment]
Okay, thanks you!
