### ISSUE TITLE
Error spanw ENOENT

### ISSUE THREAD

**Issue by AntJanus** [thnew/Pdf2Png#2]
I'm using this locally (and then pushing it out to production); however, I was caught with this error:

``` js
{
  success: false,
  error: 'Error converting pdf to png: Error: spawn ENOENT'
}
```

Any ideas on how to fix it?

**Comment by thnew** [comment]
Does this happen with any PDF file?

**Comment by AntJanus** [comment]
@thnew so, I went through a ton of trouble to figure out what was happening and had to build my own wrapper in the end. I think the problem in this case was my Windows use and some issues with that (Ghostscript wouldn't run correctly).

I'll go ahead and close this out because I can't provide any helpful info on it :/ sorry.
