### ISSUE TITLE
How do you deal with multipage PDFs?

### ISSUE THREAD

**Issue by daluu** [thnew/Pdf2Png#3]
With the sample code, it seems to just convert the 1st page of the PDF to PNG.

**Comment by thnew** [comment]
no it doesn't, you could fork it and include new parameters and then you have to go to where i call exec() and pass your parameters to '-dFirstPage=1 -dLastPage=1'. Or you determine the amount of pages using my extension https://github.com/thnew/pdf_page_count or you can the exec() part put of my extension, which is also using ghostscript.
