### ISSUE TITLE
More than one page 

### ISSUE THREAD

**Issue by JoK-rgb** [thnew/Pdf2Png#6]
Is it possible to convert a multiple page pdf file into pngs? For example a 3 site pdf would create "test(1).png", "test(2).png" and "test(3).png".

So far I was only be able to convert the first page of a pdf file.

**Comment by thnew** [comment]
no it doesn't, you could fork it and include new parameters and then you have to go to where i call exec() and pass your parameters to '-dFirstPage=1 -dLastPage=1'. Or you determine the amount of pages using my extension https://github.com/thnew/pdf_page_count or you can the exec() part put of my extension, which is also using ghostscript.

**Comment by dipendra210** [comment]
I also need to convert multiple pdf page into pngs.
Can somebody help me?
Thanks in advance.

**Comment by dipendra210** [comment]
I implemented pdf2png.js by followed thnew's opinion.
So, it works well ( only when you input option for { returnFilePath: true } )
Here is my code.
**pdf2png.js**
var exec = require('child_process').exec;
var tmp = require('tmp');
var fs = require('fs');
var filesource = require('filesource');

var initialized = false;

// Add Ghostscript executables path
var projectPath = __dirname.split("\\");
projectPath.pop();
projectPath = projectPath.join("\\");

exports.ghostscriptPath = projectPath + "\\executables\\ghostScript";

// for linux compability
exports.ghostscriptPath = exports.ghostscriptPath.split("\\").join("/");

exports.convert = function() {
	var filepathOrData = arguments[0];
	var callback = arguments[1];
	var options = {};
	var pageCount = 1;
	
	var tmpFileCreated = false;
	
	if(arguments[3] != null)
	{
		options = arguments[1];
		pageCount = arguments[2]
		callback = arguments[3];
	}
	
	if(!initialized)
	{
		if(!options.useLocalGhostscript)
		{
			process.env.Path += ";" + exports.ghostscriptPath;
		}
		
		initialized = true;
	}
	
	options.quality = options.quality || 100;
	
	filesource.getDataPath(filepathOrData, function(resp){
		if(!resp.success)
		{
			callback(resp);
			return;
		}
		
		// get temporary filepath
		tmp.file({ postfix: ".png" }, function(err, imageFilepath, fd) {
			if(err)
			{
				callback({ success: false, error: "Error getting second temporary filepath: " + err });
				return;
			}

			const fileName = imageFilepath.substring(0, imageFilepath.length - 4);
		
			//exec("gs -dQUIET -dPARANOIDSAFER -dBATCH -dNOPAUSE -dNOPROMPT -sDEVICE=png16m -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r" + options.quality + " -dFirstPage=1 -dLastPage=2 -sOutputFile=" + imageFilepath + " " + resp.data, function (error, stdout, stderr) {
			
			exec("gs -dQUIET -dPARANOIDSAFER -dBATCH -dNOPAUSE -dNOPROMPT -sDEVICE=png16m -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r" + options.quality + " -dFirstPage=1 -dLastPage=" + pageCount + " -sOutputFile=" + fileName + "-%d.png " + resp.data, function (error, stdout, stderr) {
				// Remove temp files
				resp.clean();
				
				if(error !== null)
				{
					callback({ success: false, error: "Error converting pdf to png: " + error });
					return;
				}

				let imgPaths = [];
				for (let i = 0; i < pageCount; i++) {
					imgPaths.push(fileName + "-" + (i + 1) + ".png");
				}

				if(options.returnFilePath)
				{
					//callback({ success: true, data: imageFilepath });
					callback({ success: true, data: imgPaths });
					return;
				}
				
				var img = fs.readFileSync(imageFilepath);
				
				// Remove temp file
				fs.unlinkSync(imageFilepath);
				
				callback({ success: true, data: img });
			});
		});
	});
};

**api.js** ( calling pdf2png.convert() function )
pdfPageCount.count(targetFile, function(resp){
						if(!resp.success)
						{
							console.log("Something went wrong: " + resp.error);
							
							return;
						}
						// pdf page count
						const pageCount = resp.data;
						// orc result of each page of pdf
						let ocrResult = '';

						pdf2png.convert(targetFile, { returnFilePath: true }, pageCount, function(resp) {
							if(!resp.success) {
							        console.log("Something went wrong: " + resp.error);
							        
							        res.send( { result: "Can't handle the PDF file." } );
							}

							for (let i = 0; i < pageCount; i++) {
							    
							    console.log("Yayy the pdf got converted, now I'm gonna ocr it!");

							    Tesseract.recognize(resp.data[i])
											 .progress((p) => {
											 	//console.log('progress', p);
											 })
											 .then((result) => {
											 	ocrResult = ocrResult + result.text;
											 	if ( i === pageCount-1) {
													res.send({result: ocrResult});
											 		console.log(ocrResult);
											 	}
											 })
							}
						});

					});
