### ISSUE TITLE
ghostScript update 

### ISSUE THREAD

**Issue by matex1024** [thnew/Pdf2Png#9]
First of all great work with this npm, thank you very much @thnew . As me(@matex1024) and my friend(@eduardomourar) use this library from time to time but we don't want to fork this project or create new project based on that one, it's better to maintain this one then create clones. 
For the issue reason I just want say there is new version of ghostScript that has few important changes for out project. We tested changes of new ghostScript just please add as contributors. 
Thanks and Best Regars
MatAng

**Comment by thnew** [comment]
Great I added both of you :)
